services:
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest

    networks:
      iceberg_net:

    ports:
      - "8181:8181"

    volumes:
      - ./docker/iceberg/catalog:/catalog

    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1

      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000

      # Persist SQLite Catalog
      - uri=jdbc:sqlite:/catalog/iceberg_catalog.db

  minio:
    image: minio/minio
    container_name: minio

    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio

    networks:
      iceberg_net:
        aliases:
          - warehouse.minio

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - ./docker/minio/data:/data

    command:
      - server
      - /data
      - --console-address
      - ":9001"

  mc:
    image: minio/mc
    container_name: mc

    depends_on:
      - minio

    networks:
      iceberg_net:

    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password)
      do
          echo 'Waiting for MinIO...'
          sleep 2
      done;

      /usr/bin/mc mb minio/warehouse --ignore-existing;

      tail -f /dev/null
      "

  trino:
    image: trinodb/trino:latest
    container_name: trino

    ports:
      - "8080:8080"

    volumes:
      - ./docker/trino/config.properties:/etc/trino/config.properties
      - ./docker/trino/node.properties:/etc/trino/node.properties
      - ./docker/trino/jvm.config:/etc/trino/jvm.config
      - ./docker/trino/catalog:/etc/trino/catalog

    depends_on:
      rest:
        condition: service_healthy

    networks:
      - iceberg_net

  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-volume:/var/lib/postgresql/data
    networks:
      - iceberg_net

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
      GROQ_API_KEY: ${GROQ_API_KEY}
      ICEBERG_URI: http://iceberg-rest:8181
      S3_ENDPOINT: http://minio:9000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
    ports:
      - "8081:8080"
    command: webserver
    networks:
      - iceberg_net

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      PYTHONPATH: /opt/airflow
      GROQ_API_KEY: ${GROQ_API_KEY}
      ICEBERG_URI: http://iceberg-rest:8181
      S3_ENDPOINT: http://minio:9000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
    command: scheduler
    networks:
      - iceberg_net

  airflow-init:
    build: .

    container_name: airflow-init

    depends_on:
      - airflow-postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      GROQ_API_KEY: ${GROQ_API_KEY}
      ICEBERG_URI: http://iceberg-rest:8181
      S3_ENDPOINT: http://minio:9000
    command: db migrate

    networks:
      - iceberg_net

networks:
  iceberg_net:

volumes:
  airflow-postgres-volume:
