coordinator=true
node-scheduler.include-coordinator=true

http-server.http.port=8080

discovery.uri=http://localhost:8080

http-server.authentication.type=PASSWORD

password-authenticator.config-files=/etc/trino/password-authenticator.properties

internal-communication.shared-secret=job-intelligence-secret